swagger.yaml

[BLCR-2844](https://brandslisten.atlassian.net/browse/BLCR-2844)

[BLCR-2844][BLCR-2762] Update type of `external_id` as `string` for `ProductStatisticItem`

---

swagger.yaml

[BLCR-2840](https://brandslisten.atlassian.net/browse/BLCR-2840)

[BLCR-2840][API] Return user object after it is created

---

swagger.yaml

uuid- & and slug-param get created by tag-model

Remove unnecessary params for tag-endpoint

---

swagger.yaml

Reverts brandslisten/api-swagger#8

Revert "Remove unnecessary params for tag-endpoint"

---

swagger.yaml

[BLCR-2802](https://brandslisten.atlassian.net/browse/BLCR-2802)

[BLCR-2802] [API] Tag endpoint: listing

---

swagger.yaml

[BLCR-2859](https://brandslisten.atlassian.net/browse/BLCR-2859)
with filters

[BLCR-2859][Topics] Add Topics Endpoint

---

swagger.yaml

[ticket](https://brandslisten.atlassian.net/browse/BLCR-2802)

[BLCR-2802]Add all tags by topic

---

swagger.yaml

[BLCR-2854](https://brandslisten.atlassian.net/browse/BLCR-2854)

[BLCR-2854][Follow] Add subscriptions endpoint documentation

---

swagger.yaml

[BLCR-2870](https://brandslisten.atlassian.net/browse/BLCR-2870)

[BLCR-2870][Feedback] Create

---

swagger.yaml

- attachment field added
- get user's subscriptions

Subscriptions list

---

swagger.yaml

- remove draft annotation
- remove endpoint which doesn't exist and wouldn't

Remove User/following

---

swagger.yaml

[BLCR-2867](https://brandslisten.atlassian.net/browse/BLCR-2867)

[BLCR-2867][Containers] Followers: Notify

---

swagger.yaml

[BLCR-2926](https://brandslisten.atlassian.net/browse/BLCR-2926)

[BLCR-2926] Add case when criteria value is invalid for reviews#create

---

swagger.yaml

to:
create container/question
create container/feedback
create feedback
create container

[BLCR-2995][BLCR-2996][BLCR-2997][Api] Add slug

---

swagger.yaml

Documentation for [BLCR-3044](https://brandslisten.atlassian.net/browse/BLCR-3044)

[BLCR-3044][DOC] Set password by admins

---

swagger.yaml

[BLCR-3050](https://brandslisten.atlassian.net/browse/BLCR-3050)

[BLCR-3050] Add Schema and update some other objects

---

swagger.yaml

Add slug as configurable param to question#create
[Ticket](https://brandslisten.atlassian.net/browse/BLCR-2995)

[BLCR-2995][API] Enhancement question creation

---

swagger.yaml

[BLCR-3138](https://brandslisten.atlassian.net/browse/BLCR-3138)

[BLCR-3138] Add `test_review_introduction` to `Producttest`

---

swagger.yaml

[BLCR-3181](https://brandslisten.atlassian.net/browse/BLCR-3181)

[BLCR-3181] Update Swagger

---

swagger.yaml

[BLCR-3182](https://brandslisten.atlassian.net/browse/BLCR-3182)

[BLCR-3182] Swag

---

swagger.yaml

[BLCR-3172](https://brandslisten.atlassian.net/browse/BLCR-3172)

[BLCR-3172] Add Topic Search

---

swagger.yaml

[BLCR-3196](https://brandslisten.atlassian.net/browse/BLCR-3196)

[BLCR-3196] Filter parameters for topics

---

swagger.yaml

[Ticket](https://brandslisten.atlassian.net/browse/BLCR-3168)

[BLCR-3168][API] Use container endpoint to return product info

---

swagger.yaml

[BLCR-3203](https://brandslisten.atlassian.net/browse/BLCR-3203)
also includes documentation for https://github.com/brandslisten/bl-modular-api/pull/303

[BLCR-3203][Producttests] Update swagger

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3215
Relates to https://github.com/brandslisten/bl-modular-api/pull/309

[BLCR-3215][API] Update of teaser text params

---

swagger.yaml

https://github.com/brandslisten/bl-modular-api/pull/310

[][Mapper] Nested assoc helper documentation

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3241
Relates to https://github.com/brandslisten/bl-modular-api/pull/329

Updated PT

---

swagger.yaml

[BLCR-3246](https://brandslisten.atlassian.net/browse/BLCR-3246)

[BCLR-3246] Add documentation

---

swagger.yaml

[BLCR-3126](https://brandslisten.atlassian.net/browse/BLCR-3126)

[BLCR-3126][Reviews] Add Dokumentation

---

swagger.yaml

[BLCR-3253](https://brandslisten.atlassian.net/browse/BLCR-3253)

[BLCR-3253] Add `correct_answer_uuid`, ` correct_answer`

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3288

API: Update /product_tests to return new sidebar fields

---

swagger.yaml

[BLCR-3244] Added minLength and maxLength to participation_requests and reviews
[BLCR-3244]: https://brandslisten.atlassian.net/browse/BLCR-3244

[BLCR-3244] Added minLength and maxLength

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3288

[BLCR-3288] Update of PT response json: grouped product and sponsor info

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3022

[BLCR-3022][API] Enhance /topics sorting facilities

---

swagger.yaml

[Ticket](https://brandslisten.atlassian.net/browse/BLCR-3248)

[BLCR-3248] Add documentation for 401 expired session response

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3333
PR => modular-api https://github.com/brandslisten/bl-modular-api/pull/365

[BLCR-3333] Adjust Product test API to include new sponsor link field from WFT

---

swagger.yaml

[BLCR-3398](https://brandslisten.atlassian.net/browse/BLCR-3398)

[BLCR-3398][Containers] Update documantation

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3460

[BLCR-3460] Added articles api

---

swagger.yaml

[BLCR-3461](https://brandslisten.atlassian.net/browse/BLCR-3461)

[BLCR-3461][Article(Answers)] Add Endpoint

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3463

[BLCR-3463] updated comments on articles have locales

---

swagger.yaml

[BLCR-3470](https://brandslisten.atlassian.net/browse/BLCR-3470)

[BLCR-3470] Add ratings

---

swagger.yaml

[BLCR-3469](https://brandslisten.atlassian.net/browse/BLCR-3469)

[API] voting on articles

---

swagger.yaml

[DB-151](https://brandslisten.atlassian.net/browse/DB-151)

[DB-151] Add FAQ response and general fixes

---

swagger.yaml

[DB-148](https://brandslisten.atlassian.net/browse/DB-148)

[DB-148][API] Add new and missing properties

---

swagger.yaml

[BLCR-3652](https://brandslisten.atlassian.net/browse/BLCR-3652)

New Endpoint for comment list

---

swagger.yaml

https://github.com/brandslisten/bl-core-logic/pull/316l

vote create

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3674

Users#index + random sorting direction

---

swagger.yaml

Summary
---
Add new `/statistic` endpoint
Jira: [BLCR-3678](https://brandslisten.atlassian.net/browse/BLCR-3678)

[BLCR-3678] Add new statistic endpoint

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3707

Add infos about user rating to GET /contributions/{uuid}

---

swagger.yaml

[DB-326](https://brandslisten.atlassian.net/browse/DB-326)

sticky stream items

---

swagger.yaml

[BLCR-3749](https://brandslisten.atlassian.net/browse/BLCR-3749)

[BLCR-3749][API] Update user Swagger model

---

swagger.yaml

Summary
---
Add new endpoints:
- `/tags/most_valuable`
- `/categories/{uuid}/tags/most_valuable`
Jira: [BLCR-3745](https://brandslisten.atlassian.net/browse/BLCR-3745)

[BLCR-3745] Add endpoints for most valuable tags

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3756

[BLCR-3756] Added edited by/at attrs

---

swagger.yaml

[DB-418](https://brandslisten.atlassian.net/browse/DB-418)

remove un approved commit

---

swagger.yaml

Summary
---
Jira: [DB-473](https://brandslisten.atlassian.net/browse/DB-473)

[DB-473] Add schema support for comments endpoint

---

swagger.yaml

Summary
---
Jira: [DB-467](https://brandslisten.atlassian.net/browse/DB-467)

[DB-467] Add type filter to user subscriptions endpoint

---

swagger.yaml

[BLCR-3774](https://brandslisten.atlassian.net/browse/BLCR-3774)

Document Categories endpoint

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3789

Add dicussion_count in response

---

swagger.yaml

https://brandslisten.atlassian.net/browse/DB-541

Add role_badgeto user

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3769

[BLCR-3769][BE][API] Add edited to comments endpoint(s)

---

swagger.yaml

[BLCR-3812](https://brandslisten.atlassian.net/browse/BLCR-3812)

Endpoint for most valuable categories

---

swagger.yaml

[BLCR-3810](https://brandslisten.atlassian.net/browse/BLCR-3810)

[BLCR-3810][API] Add swagger

---

swagger.yaml

[BLCR-3810](https://brandslisten.atlassian.net/browse/BLCR-3810)

[BLCR-3810][API] Missed tags

---

swagger.yaml

[BLCR-3861](https://brandslisten.atlassian.net/browse/BLCR-3861)

BLCR-3861: Add api endpoint for my feed counter

---

swagger.yaml

[BLCR-3862](https://brandslisten.atlassian.net/browse/BLCR-3862)

[BLCR-3862][API] Add Category recommended endpoint

---

swagger.yaml

[BLCR-3867](https://brandslisten.atlassian.net/browse/BLCR-3867)

[BLCR-3867][API] Add statistics to tag mapper

---

swagger.yaml

[BLCR-3840](https://brandslisten.atlassian.net/browse/BLCR-3840)

[BLCR-3840][API] Add mark as read endpoint documentation

---

swagger.yaml

[BLCR-3862](https://brandslisten.atlassian.net/browse/BLCR-3862)

[BLCR-3862][API] typo

---

swagger.yaml

[BLCR-3891](https://brandslisten.atlassian.net/browse/BLCR-3891)

[BLCR-3891] Activities via POST

---

swagger.yaml

Summary
---
Jira: [BLCR-3865](https://brandslisten.atlassian.net/browse/BLCR-3865)

[BLCR-3865] Add sorting to categories endpoint

---

swagger.yaml

[BLCR-3868](https://brandslisten.atlassian.net/browse/BLCR-3868)

 Add answers/{uuid}/page endpoint

---

swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3870

Add user activity statistics to endpoint

---

swagger.yaml

Summary
---
Jira: [BLCR-3822](https://brandslisten.atlassian.net/browse/BLCR-3822)

[BLCR-3822] Add private groups endpoint

---

main.yaml
parameters/Page.yaml
parameters/PerPage.yaml
paths/ad_hoc_messages.yaml
paths/articles.yaml
paths/categories.yaml
paths/categories/most_valuable.yaml
paths/categories/recommended.yaml
paths/categories/tags/most_valuable.yaml
paths/containers/answer_index.yaml
paths/containers/articles.yaml
paths/private_groups.yaml
paths/tags/most_valuable.yaml
paths/topics.yaml
paths/topics/search.yaml
paths/users.yaml
paths/users/activities.yaml
paths/users/activities/index.yaml
schemas/PrivateGroupsResponse.yaml
swagger.yaml

[BLCR-3875](https://brandslisten.atlassian.net/browse/BLCR-3875)

[BLCR-3875][API] Add private_groups index

---

paths/personal_feeds/count.yaml
swagger.yaml

[BLCR-3898](https://brandslisten.atlassian.net/browse/BLCR-3898)

Change GET /personal_feeds/count to include unseen & unread

---

schemas/PrivateGroup.yaml
swagger.yaml

[BLCR-3875](https://brandslisten.atlassian.net/browse/BLCR-3875)

[BLCR-3875][API] Add authorized actions

---

schemas/Answer.yaml
schemas/BaseTopic.yaml
swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3878

Add forking reason to topic endpoint

---

schemas/Answer.yaml
swagger.yaml

[BLCR-3879](https://brandslisten.atlassian.net/browse/BLCR-3879)

Add forked indicator to answer enpoint

---

parameters/Attachments.yaml
parameters/FeaturedImages.yaml
parameters/_index.yaml
paths/feedbacks.yaml
paths/questions.yaml
swagger.yaml

[BLCR-3928](https://brandslisten.atlassian.net/browse/BLCR-3928)

[BLCR-3928][API] Update attachment ids api

---

paths/categories/most_valuable.yaml
swagger.yaml

[BLCR-3782](https://brandslisten.atlassian.net/browse/BLCR-3782)

Create endpoint for FAQ overview page

---

main.yaml
paths/users/most_active_users.yaml
swagger.yaml

[BLCR-3929](https://brandslisten.atlassian.net/browse/BLCR-3929)

Endpoint for most active users

---

main.yaml
paths/config.yaml
schemas/Configuration.yaml
swagger.yaml

Summary
---
Jira: [BLCR-3903](https://brandslisten.atlassian.net/browse/BLCR-3903)

[BLCR-3903] Create config endpoint

---

main.yaml
paths/categories/most_valuable.yaml
paths/community_statistics.yaml
swagger.yaml

[BLCR-3902](https://brandslisten.atlassian.net/browse/BLCR-3902)

new endpoint for community statistics

---

main.yaml
paths/static_page.yaml
schemas/StaticPage.yaml
swagger.yaml

Summary
---
Jira: [BLCR-3882](https://brandslisten.atlassian.net/browse/BLCR-3882)

[BLCR-3882] Add static_pages/:id endpoint

---

main.yaml
paths/tags.yaml
paths/tags/search.yaml
swagger.yaml

[BLCR-3950](https://brandslisten.atlassian.net/browse/BLCR-3950)

Add tag search

---

main.yaml
parameters/Page.yaml
parameters/PerPage.yaml
paths/static_pages.yaml
schemas/StaticPage.yaml
swagger.yaml

Summary
---
Jira: [BLCR-3883](https://brandslisten.atlassian.net/browse/BLCR-3883)

[BLCR-3883] Add static_pages endpoint

---

paths/static_pages.yaml
swagger.yaml

Summary
---
Jira: [BLCR-3883](https://brandslisten.atlassian.net/browse/BLCR-3883)

[BLCR-3883] Add language filter to static_pages endpoint

---

schemas/Configuration.yaml
swagger.yaml

Summary
---
Jira: [BLCR-3961](https://brandslisten.atlassian.net/browse/BLCR-3961)

[BLCR-3961] Add asset and attachment config to config endpoint

---

paths/users.yaml
schemas/User.yaml
swagger.yaml

Summary
---
Jira: [BLCR-3906](https://brandslisten.atlassian.net/browse/BLCR-3906)

[BLCR-3906] Add filter and statistics to /users

---

paths/search.yaml
swagger.yaml

[BLCR-3956](https://brandslisten.atlassian.net/browse/BLCR-3956)

[BLCR-3956][API] Update API documentation

---

schemas/Configuration.yaml
swagger.yaml

20210908 rr blcr 3997

---

main.yaml
paths/topics/most_popular_topics.yaml
schemas/MostPopularTopicResponse.yaml
schemas/MostPopularTopicsResponse.yaml
swagger.yaml

[BLCR-3908](https://brandslisten.atlassian.net/browse/BLCR-3908)

most popular topics

---

paths/questions.yaml
swagger.yaml

https://brandslisten.atlassian.net/browse/BLCR-3991

Forking comments via API

---

paths/search.yaml
swagger.yaml

[BLCR-3956](https://brandslisten.atlassian.net/browse/BLCR-3956)

[BLCR-3956][API] Update search descriptions

---

paths/question.yaml
swagger.yaml

[BLCR-4010](https://brandslisten.atlassian.net/browse/BLCR-4010)

[BLCR-4010][API] Add schema to question update endpoint

---

paths/users.yaml
swagger.yaml

[BLCR-4012](https://brandslisten.atlassian.net/browse/BLCR-4012)

filter for about_me

---

paths/tags.yaml
swagger.yaml

[BLCR-4020](https://brandslisten.atlassian.net/browse/BLCR-4020)

[BLCR-4020][API] Allow integer for required topics

---

schemas/Category.yaml
schemas/PrivateGroup.yaml
swagger.yaml

Summary
---
Jira: [BLCR-3918](https://brandslisten.atlassian.net/browse/BLCR-3918) & [BLCR-3919](https://brandslisten.atlassian.net/browse/BLCR-3919)

[BLCR-3918] Add button_variant to private groups and categories

---

paths/users/notifications.yaml
swagger.yaml

Summary
---
Jira: [BLCR-3963](https://brandslisten.atlassian.net/browse/BLCR-3963)

[BLCR-3963] Add filter and grouped sorting to notifications endpoint

---

schemas/Notification.yaml
swagger.yaml

Summary
---
Jira: [BLCR-3963](https://brandslisten.atlassian.net/browse/BLCR-3963)

[BLCR-3963] Add UUID to notification schema

---

schemas/AdHocMessages.yaml
swagger.yaml

[BLCR-3896](https://brandslisten.atlassian.net/browse/BLCR-3896)

[BLCR-3896][API] Update AdHocMessage response

---

main.yaml
paths/search/statistics.yaml
swagger.yaml

[BLCR-4045](https://brandslisten.atlassian.net/browse/BLCR-4045)

[BLCR-4045][API] Add search statistics endpoint

---

main.yaml
paths/tags/categories/most_valuable.yaml
swagger.yaml

[BLCR-4084](https://brandslisten.atlassian.net/browse/BLCR-4084)

most valuable categories of a tag

---

paths/unique_identifiers.yaml
swagger.yaml

add user to Slug API

---

paths/product_tests.yaml
paths/search.yaml
paths/tags.yaml
paths/tags/categories/most_valuable.yaml
paths/topics/most_popular_topics.yaml
paths/topics/search.yaml
swagger.yaml

Summary
---
Jira: [BLCR-4072](https://brandslisten.atlassian.net/browse/BLCR-4072)

[BLCR-4072] Update per_page

---

schemas/Producttest.yaml
swagger.yaml

Summary
---
Jira: [BLCR-4162](https://brandslisten.atlassian.net/browse/BLCR-4162)

[BLCR-4162] Add "type" to product tests

---

schemas/ProductReview.yaml
schemas/Review.yaml
swagger.yaml

Summary
---
Jira: [BLCR-4174](https://brandslisten.atlassian.net/browse/BLCR-4174)

[BLCR-4174] Add slug field to product reviews endpoint
